// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *Contract) setDefaults() {
	{
		val := bool(false)
		s.Accepted = val
	}
	{
		val := bool(false)
		s.Fulfilled = val
	}
}

// setDefaults set default value of fields.
func (s *Meta) setDefaults() {
	{
		val := int(1)
		s.Page = val
	}
	{
		val := int(10)
		s.Limit = val
	}
}

// setDefaults set default value of fields.
func (s *PatchShipNavReq) setDefaults() {
	{
		val := ShipNavFlightMode("CRUISE")
		s.FlightMode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ShipCrew) setDefaults() {
	{
		val := ShipCrewRotation("STRICT")
		s.Rotation = val
	}
}

// setDefaults set default value of fields.
func (s *ShipNav) setDefaults() {
	{
		val := ShipNavFlightMode("CRUISE")
		s.FlightMode = val
	}
}
